modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
showAsResourcePack=false

[[mods]] #mandatory
modId="usts_mod" #mandatory
version="1.2.0" #mandatory
displayName="USTS Mod" #mandatory
logoFile="usts_mod.png" #optional

credits="Made by Octo" #optional
authors="Octo" #optional
description='''A mod for the USTS Discord.

Gamerules:
    -usts_mod.zeusMode (Default: false)
        false: Disabled.
        true: Players will be struck by lightning for each item they pick up.
    -usts_mod.lightningRodHelmet (Default: 2)
        0: Disabled (Players will still be able to equip the lightning rod in their head slot).
        1: When lightning strikes, all players that are wearing a lightning rod in their helmet slot and are visible to the sky will be struck by lightning.
        2: When lightning strikes, a random player wearing a lightning rod will be struck by lightning. If the chosen player is not visible to the sky, no one will be struck.'''
displayTest="MATCH_VERSION"

[[dependencies.usts_mod]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.usts_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
